DOWNLOAD("general.ks").
DOWNLOAD("manoeuvre.ks").
RUN general.ks.
RUN manoeuvre.ks.

NOTIFY("ADDING NODE...").
SET dv TO MNV_HOHMANN_DV(100000).
SET n1 TO NODE(TIME:SECONDS + ETA:APOAPSIS, 0, 0, dv[0]).
ADD n1.
NOTIFY("EXECUTING FIRST NODE...").
MNV_EXEC_NODE(TRUE).
NOTIFY("DONE FIRST NODE!").
SET n2 TO NODE(TIME:SECONDS + ETA:PERIAPSIS, 0, 0, dv[1]).
ADD n2.
NOTIFY("EXECUTING SECOND NODE...").
MNV_EXEC_NODE(TRUE).
NOTIFY("DONE SECOND NODE!").
