WAIT UNTIL ETA:APOAPSIS < 20.

SET circularization TO PROGRADE.
LOCK STEERING TO circularization. WAIT 5.
LOCK THROTTLE TO 1.
WAIT UNTIL PERIAPSIS > 900000.
LOCK THROTTLE TO 0.1.
WAIT UNTIL PERIAPSIS > 1000000.
LOCK THROTTLE TO 0.

WAIT UNTIL ETA:PERIAPSIS < 10.
SET adjust TO RETROGRADE.
LOCK STEERING TO adjust. WAIT 5.
LOCK THROTTLE TO 0.3.
WAIT UNTIL APOAPSIS < 1010000.
LOCK THROTTLE TO 0.
